export const PUSH_PERSON = "PUSH_PERSON"
export const DELETE_PERSON_FROM_DATA = "DELETE_PERSON_FROM_DATA"

export const ADD_TO_CART = "ADD_TO_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"